### Jupyter Notebook
This brief notebook showcases key Jupyter features. Hold onto these concepts as we transition to the Marimo demo.

In [8]:
import polars as pl
import pandas as pd

print(f'Polars version {pl.__version__}')
print(f'Pandas version {pd.__version__}')

Polars version 1.42.1
Pandas version 3.0.3

In [12]:
x = 1
print(f'{x = }')

x = 1

In [10]:
x = 3
print(f'{x = }')

x = 3

### What is x?
You can’t reliably predict the value of x to be printed below without knowing sequence that the cells above (or elsewhere in this notebook) were run.

In [13]:
print(f'{x = }')

x = 1

### Hello World of dataframes
Multiplication tables are often the first structured table people learn

In [5]:
df_pandas = (
    pd.DataFrame({str(i): [j * i for j in range(11)] for i in range(11)}, dtype='uint8')
)
df_pandas # displays columns, index. No data types or dataframe shape

    0   1   2   3   4   5   6   7   8   9   10
0   0   0   0   0   0   0   0   0   0   0    0
1   0   1   2   3   4   5   6   7   8   9   10
2   0   2   4   6   8  10  12  14  16  18   20
3   0   3   6   9  12  15  18  21  24  27   30
4   0   4   8  12  16  20  24  28  32  36   40
5   0   5  10  15  20  25  30  35  40  45   50
6   0   6  12  18  24  30  36  42  48  54   60
7   0   7  14  21  28  35  42  49  56  63   70
8   0   8  16  24  32  40  48  56  64  72   80
9   0   9  18  27  36  45  54  63  72  81   90
10  0  10  20  30  40  50  60  70  80  90  100

### Dataframe displays in Jupyter
The Pandas DataFrame above doesn’t display its datatypes or shape. The Polars DataFrame below includes both. Each DataFrame is simply a different representation of the same experimental data.

In [14]:
df_polars = pl.from_pandas(df_pandas)
df_polars  # no index with polars. display has columns,  data types or shape

shape: (11, 11)
┌─────┬─────┬─────┬─────┬───┬─────┬─────┬─────┬─────┐
│ 0   ┆ 1   ┆ 2   ┆ 3   ┆ … ┆ 7   ┆ 8   ┆ 9   ┆ 10  │
│ --- ┆ --- ┆ --- ┆ --- ┆   ┆ --- ┆ --- ┆ --- ┆ --- │
│ u8  ┆ u8  ┆ u8  ┆ u8  ┆   ┆ u8  ┆ u8  ┆ u8  ┆ u8  │
╞═════╪═════╪═════╪═════╪═══╪═════╪═════╪═════╪═════╡
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ 0   ┆ 1   ┆ 2   ┆ 3   ┆ … ┆ 7   ┆ 8   ┆ 9   ┆ 10  │
│ 0   ┆ 2   ┆ 4   ┆ 6   ┆ … ┆ 14  ┆ 16  ┆ 18  ┆ 20  │
│ 0   ┆ 3   ┆ 6   ┆ 9   ┆ … ┆ 21  ┆ 24  ┆ 27  ┆ 30  │
│ 0   ┆ 4   ┆ 8   ┆ 12  ┆ … ┆ 28  ┆ 32  ┆ 36  ┆ 40  │
│ …   ┆ …   ┆ …   ┆ …   ┆ … ┆ …   ┆ …   ┆ …   ┆ …   │
│ 0   ┆ 6   ┆ 12  ┆ 18  ┆ … ┆ 42  ┆ 48  ┆ 54  ┆ 60  │
│ 0   ┆ 7   ┆ 14  ┆ 21  ┆ … ┆ 49  ┆ 56  ┆ 63  ┆ 70  │
│ 0   ┆ 8   ┆ 16  ┆ 24  ┆ … ┆ 56  ┆ 64  ┆ 72  ┆ 80  │
│ 0   ┆ 9   ┆ 18  ┆ 27  ┆ … ┆ 63  ┆ 72  ┆ 81  ┆ 90  │
│ 0   ┆ 10  ┆ 20  ┆ 30  ┆ … ┆ 70  ┆ 80  ┆ 90  ┆ 100 │
└─────┴─────┴─────┴─────┴───┴─────┴─────┴─────┴─────┘

### Bring your own data viz
Jupyter does not provide built-in data visualization tools. 
Libraries like Plotly, Matplotlib, Altair or others are required.

In [7]:
import plotly 
import plotly.graph_objects as go
print(f'Plotly version {plotly.__version__}')

x_values = df_polars['1'].to_list()
fig = go.Figure([
        go.Scatter(
        x=x_values,
        y=df_polars[c].to_list(),
        mode='lines',
        name=c + '*X')
    for c in df_polars.columns
])
fig.update_layout(
    title='3rd Grade Times Table - 0s included for STEM students',
    xaxis_title='Factor',
    yaxis_title='Product',
    template='simple_white',
    hovermode='x unified',
    showlegend=False,
    width=(w:=600),
    height=w,
    margin=dict(r=90))
fig.update_xaxes(
    range=[min(x_values), max(x_values) + 1],
    tickmode='array',
    tickvals=x_values,
    ticktext=[str(value) for value in x_values],
    showgrid=True,
    gridcolor='lightgray',
    griddash='dash')
fig.update_yaxes(
    tickmode='array',
    tickvals=list(range(0, 101, 10)),
    showgrid=True,
    gridcolor='lightgray',
    griddash='dash')
fig.update_traces(cliponaxis=False)

for column in df_polars.columns:
    fig.add_annotation(
        x=x_values[-1],
        y=df_polars[column].to_list()[-1],
        text=column + ' X',
        showarrow=False,
        xanchor='left',
        xshift=10,
        yanchor='middle')

fig

Plotly version 6.8.0