### Jupyter Notebook
This brief notebook showcases key Jupyter features. Hold onto these concepts as we transition to the Marimo demo.

In [10]:
import math
import polars as pl
import pandas as pd
import plotly 
import plotly.graph_objects as go
import plotly.express as px

import plotly.offline as pyo
pyo.init_notebook_mode()

print(f'Polars version {pl.__version__}')
print(f'Pandas version {pd.__version__}')
print(f'Plotly version {plotly.__version__}')

Polars version 1.42.1
Pandas version 3.0.3
Plotly version 6.8.0

In [20]:
x = 1
print(f'{x = }')

x = 1

In [12]:
x = 4
print(f'{x = }')

x = 4

### What is x?
You can’t reliably predict the value of x to be printed below without knowing sequence that the cells above (or elsewhere in this notebook) were run.

In [21]:
print(f'{x = }')

x = 1

### Pandas Dataframe
Times tables were the first example of tabular data I ever learned. Don’t let the Pandas index in the first column throw you off.

Credit to my outstanding third‑grade teacher at Christ the King Elementary School in Westmere, NY, **Patricia Thomas**.

In [14]:
df_pandas = (
    pd.DataFrame( 
        {str(i): [j * i for j in range(1, 10)] for i in range(1,10)}, 
        dtype='uint8'
    )
)
df_pandas # displays columns, index. No data types or dataframe shape

   1   2   3   4   5   6   7   8   9
0  1   2   3   4   5   6   7   8   9
1  2   4   6   8  10  12  14  16  18
2  3   6   9  12  15  18  21  24  27
3  4   8  12  16  20  24  28  32  36
4  5  10  15  20  25  30  35  40  45
5  6  12  18  24  30  36  42  48  54
6  7  14  21  28  35  42  49  56  63
7  8  16  24  32  40  48  56  64  72
8  9  18  27  36  45  54  63  72  81

### Polars dataframe
Polars dataframe show column datatypes and dataframe shape, and no index.

In [15]:
df_polars = pl.from_pandas(df_pandas)
df_polars  # no index with polars. display has columns,  data types or shape

shape: (9, 9)
┌─────┬─────┬─────┬─────┬───┬─────┬─────┬─────┬─────┐
│ 1   ┆ 2   ┆ 3   ┆ 4   ┆ … ┆ 6   ┆ 7   ┆ 8   ┆ 9   │
│ --- ┆ --- ┆ --- ┆ --- ┆   ┆ --- ┆ --- ┆ --- ┆ --- │
│ u8  ┆ u8  ┆ u8  ┆ u8  ┆   ┆ u8  ┆ u8  ┆ u8  ┆ u8  │
╞═════╪═════╪═════╪═════╪═══╪═════╪═════╪═════╪═════╡
│ 1   ┆ 2   ┆ 3   ┆ 4   ┆ … ┆ 6   ┆ 7   ┆ 8   ┆ 9   │
│ 2   ┆ 4   ┆ 6   ┆ 8   ┆ … ┆ 12  ┆ 14  ┆ 16  ┆ 18  │
│ 3   ┆ 6   ┆ 9   ┆ 12  ┆ … ┆ 18  ┆ 21  ┆ 24  ┆ 27  │
│ 4   ┆ 8   ┆ 12  ┆ 16  ┆ … ┆ 24  ┆ 28  ┆ 32  ┆ 36  │
│ 5   ┆ 10  ┆ 15  ┆ 20  ┆ … ┆ 30  ┆ 35  ┆ 40  ┆ 45  │
│ 6   ┆ 12  ┆ 18  ┆ 24  ┆ … ┆ 36  ┆ 42  ┆ 48  ┆ 54  │
│ 7   ┆ 14  ┆ 21  ┆ 28  ┆ … ┆ 42  ┆ 49  ┆ 56  ┆ 63  │
│ 8   ┆ 16  ┆ 24  ┆ 32  ┆ … ┆ 48  ┆ 56  ┆ 64  ┆ 72  │
│ 9   ┆ 18  ┆ 27  ┆ 36  ┆ … ┆ 54  ┆ 63  ┆ 72  ┆ 81  │
└─────┴─────┴─────┴─────┴───┴─────┴─────┴─────┴─────┘

### Bring your own data viz
Jupyter does not provide built-in data visualization tools. 
Libraries like Plotly, Matplotlib, Altair or others are required.

In [16]:

x_values = df_polars['1'].to_list()
fig = go.Figure([
        go.Scatter(
        x=x_values,
        y=df_polars[c].to_list(),
        mode='lines',
        name=c + '*X')
    for c in df_polars.columns
])
fig.update_layout(
    title='3rd Grade Times Table',
    xaxis_title='Factor',
    yaxis_title='Product',
    template='simple_white',
    hovermode='x unified',
    showlegend=False,
    width=(w:=600),
    height=w,
    margin=dict(r=90))
fig.update_xaxes(
    range=[min(x_values)-0.5, max(x_values)+0.5],
    tickmode='array',
    tickvals=x_values,
    ticktext=[str(value) for value in x_values],
    )
fig.update_yaxes(
    tickmode='array',
    tickvals=list(range(0, 101, 10)),
    showgrid=True,
    gridcolor='lightgray',
    griddash='dash')
fig.update_traces(cliponaxis=False)

for column in df_polars.columns:
    fig.add_annotation(
        x=x_values[-1],
        y=df_polars[column].to_list()[-1],
        text=column + ' X',
        showarrow=False,
        xanchor='left',
        xshift=10,
        yanchor='middle')

fig.show()

In [17]:
sample_size = 2**15
print(f'{sample_size = }')
df = (
    pl.DataFrame({
        'X': [(360 * i) / sample_size for i in range(sample_size)],
        'SINE': [math.sin((2* math.pi * i) / sample_size) for i in range(sample_size)],
        'COS': [math.cos((2* math.pi * i) / sample_size) for i in range(sample_size)]
    })
)
df

sample_size = 32768

shape: (32_768, 3)
┌────────────┬───────────┬─────┐
│ X          ┆ SINE      ┆ COS │
│ ---        ┆ ---       ┆ --- │
│ f64        ┆ f64       ┆ f64 │
╞════════════╪═══════════╪═════╡
│ 0.0        ┆ 0.0       ┆ 1.0 │
│ 0.010986   ┆ 0.000192  ┆ 1.0 │
│ 0.021973   ┆ 0.000383  ┆ 1.0 │
│ 0.032959   ┆ 0.000575  ┆ 1.0 │
│ 0.043945   ┆ 0.000767  ┆ 1.0 │
│ …          ┆ …         ┆ …   │
│ 359.945068 ┆ -0.000959 ┆ 1.0 │
│ 359.956055 ┆ -0.000767 ┆ 1.0 │
│ 359.967041 ┆ -0.000575 ┆ 1.0 │
│ 359.978027 ┆ -0.000383 ┆ 1.0 │
│ 359.989014 ┆ -0.000192 ┆ 1.0 │
└────────────┴───────────┴─────┘

In [18]:

color_cosine = '#4e79a7' #  (blue)
color_sine =   '#e15759'  # (red) 
fig = px.line(
    df,
    'X',
    ['SINE', 'COS'],
    title='Sine and Cosine Functions',
    template='simple_white',
    width=800, 
    labels={
        'X': 'Degrees',
        'value': 'Function Value',
        'variable': ''
    },
    line_shape='hvh',
    color_discrete_map = {'SINE':color_sine, 'COS': color_cosine}
) 

fig.update_xaxes(
    range=[-10, 370],
    tickmode='array',
    tickvals=list(range(0, 361, 30)),
    ticktext=[str(value) for value in range(0, 361, 30)],
    showgrid=True,  # for y-axis, set showgrid to false, and use add_hline for customization
)

fig.update_yaxes(
    range=[-1.1, 1.1],
    tickmode='array',
    tickvals=[
        -1, 
        -math.sqrt(3)/2, 
        -math.sqrt(2)/2, 
        -0.5,
        0, 
        0.5, 
        math.sqrt(2)/2, 
        math.sqrt(3)/2, 
        1
    ],
    ticktext=[
        '-1', 
        '-√3/2', 
        '-1/√2',
        '-0.5',
        '0', 
        '0.5', 
        '1/√2',
        '√3/2', 
        '1'
    ],
    showgrid=False,
)

hline_args = dict(
    line_width=2,
    line_dash='solid', 
    line_color='#808080'
)
fig.add_hline(y=-1, **hline_args)
fig.add_hline(y=-math.sqrt(3)/2, **hline_args)
fig.add_hline(y=-1/math.sqrt(2), **hline_args)
fig.add_hline(y=-0.5, **hline_args)
fig.add_hline(y=0, **hline_args)
fig.add_hline(y=0.5, **hline_args)
fig.add_hline(y=1/math.sqrt(2), **hline_args)
fig.add_hline(y=math.sqrt(3)/2, **hline_args)
fig.add_hline(y=1, **hline_args)

xvals = [x for x in range(0, 390,30)] + [45, 225]
yvals_sin = [math.sin(2*math.pi*x/360) for x in xvals]
yvals_cos = [math.cos(2*math.pi*x/360) for x in xvals]

fig.add_trace(go.Scatter(
    x= xvals,
    y=yvals_sin,
    mode='markers',
    marker=dict(size=10, color = color_sine),
    showlegend=False 
    )
)

fig.add_trace(go.Scatter(
    x= xvals,
    y=yvals_cos,
    mode='markers',
    marker=dict(size=10, color = color_cosine),
    showlegend=False
    )
)

fig.show()

### Jupyter Summary
- No reactive execution model
- Notebook file size is ~8 MB when saved with outputs and visualizations
- Drops to ~10 KB when outputs are cleared before saving
- Marimo notebooks save only Python code—no multi‑megabyte JSON figure blobs—which makes them far more git‑friendly
- Jupyter supports Julia, Python, and R; Marimo supports Python only, with focused, streamlined support

#### Marimo saves only code, freeing significant disk space
#### Jupyter notebooks can exceed git file‑size limits
#### By storing pure Python, Marimo is inherently more git‑friendly